### ISSUE TITLE
[Feature Request] Aggregate trains per station

### ISSUE THREAD

**Issue by narulaskaran** [atulsmadhugiri/ChooChoo#3]
![image](https://github.com/user-attachments/assets/353fee87-13f5-4e9d-aa27-2316698600b6)
Each station should include all the train lines in a single card. Having one card per station + train type combination makes the list harder to navigate.

**Comment by atulsmadhugiri** [comment]
I agree, always intended to do this but was putting it off.

Will prioritize since I need to merge stops at same station before I implement favorite/pinned stations.

**Comment by atulsmadhugiri** [comment]
This has been done. Changes have been pushed to `main` and a release has been made.

Grouped `MTAStop`s into `MTAStation`s by `complexID`. There's still some work to do in how the "merged" stations are presented in UI, but things should be functional for now.
